site_name: OpenKitten Docs
theme: 'material'
pages:
- Home: index.md
- 'Web':
  - 'Leopard Basics': 'leopard/index.md'
  - 'Advanced routing': 'leopard/advanced-routing.md'
  - 'Errors': 'leopard/errors.md'
  - 'Configuration': 'leopard/config.md'
  - 'Request & Response': 'leopard/request-response.md'
  - 'Cookies & Sessions': 'leopard/cookies-sessions.md'
  - 'Middlwares': 'leopard/middlewares.md'
  - 'WebSocket': 'leopard/websocket.md'
  - 'HTTP client': 'puma/index.md'
  - 'Forms and file uploading': 'leopard/Multipart.md'
  - 'Caching': 'leopard/cache.md'
- Utility:
  - 'JSON using Cheetah': 'cheetah/index.md'
  - 'Async using Schrodinger': 'schrodinger/index.md'
  - 'Plain HTTP using Lynx': 'lynx/index.md'
  - 'JWT using Ocelot': 'ocelot/index.md'
  - 'Hashing using CryptoKitten': 'cryptokitten/hash.md'
  - 'TCP/SSL using Lynx': 'lynx/TCP.md'
  - 'Testing remotes using Lynx': 'lynx/remote.md'
- 'Third Party':
  - 'Jobs': 'third-party/jobs.md'
