site_name: OpenKitten Docs
theme: cinder
pages:
- Home: index.md
- 'Web':
  - 'Leopard Basics': 'leopard/index.md'
  - 'Advanced routing': 'leopard/advanced-routing.md'
  - 'Errors': 'leopard/errors.md'
  - 'Configuration': 'leopard/config.md'
  - 'Request & Response': 'leopard/request-response.md'
  - 'Cookies & Sessions': 'leopard/cookies-sessions.md'
  - Middlwares: 'leopard/middlewares.md'
  - WebSocket: 'leopard/websocket.md'
  - 'HTTP client': 'puma/index.md'
- Utility:
  - 'JSON using Cheetah': 'cheetah/index.md'
  - 'Async using Schrodinger': 'schrodinger/index.md'
  - 'Plain HTTP using Lynx': 'lynx/index.md'
- 'Third Party':
  - 'Jobs': 'third-party/jobs.md'
